### ISSUE TITLE
shall we remove the id from the param class?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#164]
martin made that suggestion. currently we keep the id twice:
a) as a member of Param
b) in the named list "params" in ParamSet

thats already a bit uncool.

what would change is the construction
so a user would write

ParamSet$new(list(f = ParamFct$new())) 

not

ParamSet$new(list(ParamFct$new(id = "f"))) 

this might also make ParamSetCollections simpler. 

i am a bit unsure here

**Comment by mb706** [comment]
Some "Sampler1D" / "SamplerHierachical" things would probably need to be rearranged because a 1D sampler would arguably not know what parameter it belongs to (or would need to be initialized with the ID). Not sure how much of a loss that is compared to the win of not having to do double bookkeeping in ParamSet though.

**Comment by berndbischl** [comment]
i dont want to remove the id now
