### ISSUE TITLE
Unclear documentation for defining Parameter subclasses

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/paradox#242]
Apologies if this already exists somewhere, or if perhaps I have missed something in the bookdown, but I am trying to define a new parameter, for example `ParamDbl`. Firstly I am unsure what arguments go in the constructor, are the arguments given in the bookdown example exhaustive for each type?

Secondly, and perhaps a separate issue, would it make sense to fill the `values` with the `default`? e.g.

```R
x <- ParamDbl$new("A",2,4,default = 3)
x$values
```

would return
```
$A [1] 3
```

**Comment by berndbischl** [comment]
First of all, the book gives a vignette-like intro to the package, for question like these always consult the formal docs so ?ParamDbl

**Comment by berndbischl** [comment]
this mentions this, 

```
#' @section Construction:
#' ```
#' ParamDbl$new(id, lower = -Inf, upper = Inf, special_vals = list(), default = NO_DEF, tags = character())
#' ```
#' Arguments of [Param], and additionally:
#'
#' * `lower` :: `numeric(1)`\cr
#'   Lower bound, can be `-Inf`.
#' * `upper` :: `numeric(1)`\cr
#'   Upper bound can be `+Inf`.
```

and thats complete (i hope)

**Comment by RaphaelS1** [comment]
Ah sorry I had looked at the `public members` section as the reference. This is slightly confusing as in `public methods` this describes all the constructors... There is also no `Construction` section which makes me wonder if perhaps I have an old version downloaded...

**Comment by berndbischl** [comment]
why dont you simply clone the repo and work on that? then as long as you pull such a problem cannot occur?

**Comment by berndbischl** [comment]
if you want to discuss the doc structure in general thats outlined here
https://github.com/mlr-org/mlr3/wiki
https://github.com/mlr-org/mlr3/wiki/Roxygen-Guide

**Comment by RaphaelS1** [comment]
Will do!

**Comment by berndbischl** [comment]
our rules might not be perfect yet, and not every package might not adhere to them perfectly, but we try

**Comment by RaphaelS1** [comment]
Understood, the second part of my question also resolved by updating

**Comment by berndbischl** [comment]
> Secondly, and perhaps a separate issue, would it make sense to fill the `values` with the `default`? e.g.

ok that's a difficult point and we discussed this a lot. the situation is this:

- ideally, defaults would be in the paramset, as they currently are, and we always set them transparently in the values. 

- the auto-filling them in "values" - from the defaults - seems natural - as you suggested here.

- for mlr3 that does not work. the problem is that the defaults are "specified" in externl package not under our control. they sometimes are not even number, but complicated heuristics. they can change behind our back thru external package update.
we have therefore opted to "document" them in a machine-readable fashion in the paramset, but not really "do" much with them. 

 - the semantics of "values" is that they passed down. and modify the TRUE defaults of the underlying piece of code. 

- if you want more options for defaults (like filling them in automatically) that can be discussed and maybe provided
