### ISSUE TITLE
Method to combine two ParamSets?

### ISSUE THREAD

**Issue by mllg** [mlr-org/paradox#38]
Is there something like this?

**Comment by berndbischl** [comment]
we had this before. with the "c" operator. and this is important to pogram on paramsets.
and you also need to be able to subset a bit

**Comment by jakob-r** [comment]
Remember: The trafo lives in the ParamSet. Combining can be managed as just both trafos have to be carried out. Subsetting is more complicated because we would have to check if the trafo requires all parameters.
But also this is no problem because, if you subset a ParamSet, it basically means that you hold the other parameters connstant so you can put the constant values in the dictionary.

However, none of this is implemented atm.

**Comment by jakob-r** [comment]
Is there anything that has to be possible which would not be possible under the restrictions I mentioned.

**Comment by jakob-r** [comment]
Approach is here: #39

**Comment by jakob-r** [comment]
Now merged.
